### ISSUE TITLE
file_edge_labels is defined twice

### ISSUE THREAD

**Issue by apurva94** [flyingdoog/PGExplainer#9]
Why does file_edge_labels have two initializations back to back in get_graph_data(dataset)?

**Comment by flyingdoog** [comment]
Could you be more specific on which file?

**Comment by apurva94** [comment]
Its in PGExplainer/dataset/pre_process_MUTAG.py as well as PGExplainer/codes/forgraph/utils.py

**Comment by flyingdoog** [comment]
Thanks for pointing it out. I just delete the first one.   In Mutag dataset, Mutagenicity_edge_labels.txt is from the original dataset, describe the types of edges.  For example, C-O is associated with 1 label and C-C is associated with another label.

In Mutagenicity_edge_gt.txt we only have two labels. Edges in side the motifs are with 1, otherwise 0.

So we use Mutagenicity_edge_gt instead of the original one for evaluation.
